language: ruby
bundler_args: --without development
before_install: gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
