language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx
    - rvm: jruby
