language: ruby
bundler_args: --without development
before_install: gem install bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
    - rvm: ruby-head
